openapi: 3.0.3
info:
  title: OpenStudio API
  description: 
    $ref: "../API - Description.md"
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    $ref: "./paths/users.yaml"
